---
apiVersion: siteconfig.open-cluster-management.io/v1alpha1
kind: ClusterInstance
metadata:
  name: "ztp-sno"
  namespace: "ztp-sno"
spec:
  baseDomain: 'local.lab'
  pullSecretRef:
    name: "ztp-pull-secret"
  clusterImageSetNameRef: 'img4.18.16-x86-64-appsub'
  sshPublicKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICluj9EqiCz2MyTOVdF0RyTZ8Zor05Osv3B5SuMpb3E/'
  clusterName: "ztp-sno"
  networkType: "OVNKubernetes"
  extraLabels:
    ManagedCluster:
      common: 'true'
      du-profile: 'latest'
      sites : 'ztp-sno'
  holdInstallation: false
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  serviceNetwork:
    - cidr: 172.32.0.0/16
  machineNetwork:
    - cidr: '192.168.125.0/24'
  additionalNTPSources:
    - 192.168.125.1
  templateRefs:
    - name: ai-cluster-templates-v1
      namespace: open-cluster-management
  nodes:
    - hostName: "zraid-bmh-1"
      role: "master"
      bmcAddress: "redfish-virtualmedia://192.168.125.1:9000/redfish/v1/Systems/local/zraid-bmh-1"
      bmcCredentialsName:
        name: "zraid-bmh-1-bmc-secret"
      bootMACAddress: "be:be:ca:fe:02:64"
      rootDeviceHints:
        deviceName: '/dev/vda'
      nodeNetwork:
        interfaces:
          - name: enp1s0
            macAddress: "be:be:ca:fe:02:64"
        config:
          interfaces:
            - name: enp1s0
              type: ethernet
              state: up
              ipv4:
                enabled: true
                dhcp: true
              ipv6:
                enabled: false
      templateRefs:
        - name: ai-node-templates-v1
          namespace: open-cluster-management
